/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;


import static databaseproject.SqlQuery.SqlQuery;
import static databaseproject.SqlQuery.SqlQuery2;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author velik
 */
public class Basvuru_Ekrani extends javax.swing.JFrame {
    
        public static Basvuru basvuru1;
        public int selecRow;
        public static ArrayList<Basvuru> basvuruArray=new ArrayList<>();

        public static ArrayList<String> telefon_arr=new ArrayList<>();
        public static ArrayList<String> cevaplama_arr=new ArrayList<>();
        public static ArrayList<String> kisi_tanımı_arr=new ArrayList<>();
        public static ArrayList<String> kamu_arr=new ArrayList<>();
        
        
        
    
   public static void radio_btn_fill(int num){
   
   kamu_arr.clear();
   kurum_tipi_combo.removeAllItems();
        
        
        try {
            
            String kamu_sorgu="select KurumAdi from Kurum where KurumTipiNo ="+num;
            ResultSet kamu_rs=SqlQuery(kamu_sorgu);
           
            
            while(kamu_rs.next()){
            
            String d = kamu_rs.getString("KurumAdi");
            kamu_arr.add(d);
            
            }
           
            
          
        } catch (Exception ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
   
   } 
        
        
        
    public static void fill_basvuru_ekrani(){
           
        telefon_arr.clear();
        
        
        try {
            String sql_query="select TelefonTipiAciklama from TelefonTipi";
          
            
            ResultSet rs=SqlQuery(sql_query);
            
            while(rs.next()){
            
            String d = rs.getString("TelefonTipiAciklama");
            telefon_arr.add(d);
            
            }
           
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        cevaplama_arr.clear();
        
        
        try {
            
            String telefon_sorgu="select CevaplamaTipiAciklama from CevaplamaTipi";
            ResultSet tel_rs=SqlQuery(telefon_sorgu);
           
            
            while(tel_rs.next()){
            
            String d = tel_rs.getString("CevaplamaTipiAciklama");
            cevaplama_arr.add(d);
            
            }
           
            
             
          
        } catch (Exception ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
            kisi_tanımı_arr.clear();
        
        
        try {
            
            String kisi_sorgu="select BasvuranTipiAciklama from BasvuranTipi";
            ResultSet kisi_rs=SqlQuery(kisi_sorgu);
           
            
            while(kisi_rs.next()){
            
            String d = kisi_rs.getString("BasvuranTipiAciklama");
            kisi_tanımı_arr.add(d);
            
            }
           
          
        } catch (Exception ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        
         
        
        }
    
    
    
    
    Login_Page login_Page =new Login_Page();
    
    /**
 
     */
    public Basvuru_Ekrani() {
        initComponents();
     jLayeredPane1.setVisible(false);
     pasaport_pane.setVisible(false);
     tc_pane.setVisible(false);
     gercek_tuzel_pane.setVisible(false);
     btn_kaydet.setEnabled(false);
     
     fill_basvuru_ekrani();
     
        for (int i = 0; i < telefon_arr.size(); i++) {
            telefon_tip_combo.addItem(telefon_arr.get(i));
        }
        
        for (int i = 0; i < cevaplama_arr.size(); i++) {
            basvuru_yolu.addItem(cevaplama_arr.get(i));
        }
        for (int i = 0; i < kisi_tanımı_arr.size(); i++) {
            kisi_tanimi.addItem(kisi_tanımı_arr.get(i));
        }
             
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kurum_tipi = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mail = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        telefon_num = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        soyad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_adres = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        uyruk = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tc_pane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tc_no = new javax.swing.JTextField();
        pasaport_pane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pasaport_no = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefon_tip_combo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        adres_combo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        basvuru_yolu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        kisi_tanimi = new javax.swing.JComboBox<>();
        gercek_tuzel_pane = new javax.swing.JPanel();
        tuzel_unvan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        kurum_tipi_combo = new javax.swing.JComboBox<>();
        btn_kaydet = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_bas_acıklama = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Başvuru Ekranı");

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Başvuru Sahibinin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        mail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        ad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        telefon_num.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        telefon_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefon_numActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Soyadı :");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Telefon Numarası:");

        soyad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyadActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Adı :");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Adres:");

        ta_adres.setColumns(20);
        ta_adres.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ta_adres.setRows(5);
        jScrollPane1.setViewportView(ta_adres);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Uyruk: ");

        uyruk.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uyruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yabancı", "T.C" }));
        uyruk.setSelectedIndex(-1);
        uyruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyrukActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tc_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("T.C. No:");
        tc_pane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 82, 32));

        tc_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tc_noKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tc_noKeyReleased(evt);
            }
        });
        tc_pane.add(tc_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 257, 41));

        pasaport_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Pasaport No:");
        pasaport_pane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 28));

        pasaport_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pasaport_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pasaport_noKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pasaport_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pasaport_noKeyTyped(evt);
            }
        });
        pasaport_pane.add(pasaport_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 260, 39));

        jLayeredPane1.setLayer(tc_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pasaport_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pasaport_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pasaport_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Telefon Tipi:");

        telefon_tip_combo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        telefon_tip_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefon_tip_comboActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Adres Tipi: ");

        adres_combo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adres_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ev", "İş" }));
        adres_combo.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLayeredPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(soyad)
                                    .addComponent(ad)
                                    .addComponent(uyruk, 0, 256, Short.MAX_VALUE))))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(telefon_num)
                            .addComponent(mail, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(adres_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefon_tip_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uyruk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(telefon_tip_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telefon_num, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(adres_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(62, 62, 62))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Başvuruya hangi yolla cevap almak istersiniz?");

        basvuru_yolu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Kişi Tanımı : ");

        kisi_tanimi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        kisi_tanimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisi_tanimiActionPerformed(evt);
            }
        });

        gercek_tuzel_pane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tuzel_unvan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Tüzel Kişi Ünvanı:");

        javax.swing.GroupLayout gercek_tuzel_paneLayout = new javax.swing.GroupLayout(gercek_tuzel_pane);
        gercek_tuzel_pane.setLayout(gercek_tuzel_paneLayout);
        gercek_tuzel_paneLayout.setHorizontalGroup(
            gercek_tuzel_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gercek_tuzel_paneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tuzel_unvan, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        gercek_tuzel_paneLayout.setVerticalGroup(
            gercek_tuzel_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gercek_tuzel_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gercek_tuzel_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuzel_unvan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Başvuru yapılan kurum tipi: ");

        kurum_tipi.add(rb1);
        rb1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rb1.setText("Kamu Kurumu Niteliğindeki Meslek Kuruluşları ");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        kurum_tipi.add(rb2);
        rb2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rb2.setText("Kamu Kurum ve Kuruluşları ");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        kurum_tipi_combo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb1)
                            .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(kurum_tipi_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gercek_tuzel_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(basvuru_yolu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kisi_tanimi, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basvuru_yolu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kisi_tanimi)
                        .addGap(3, 3, 3)))
                .addComponent(gercek_tuzel_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kurum_tipi_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb2)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        btn_kaydet.setBackground(new java.awt.Color(255, 255, 255));
        btn_kaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kaydet.setForeground(new java.awt.Color(0, 153, 0));
        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Başvurunuzu Açıklayınız: ");

        ta_bas_acıklama.setColumns(20);
        ta_bas_acıklama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ta_bas_acıklama.setRows(5);
        jScrollPane2.setViewportView(ta_bas_acıklama);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("İPTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kaydet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void telefon_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefon_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefon_numActionPerformed

    private void soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyadActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
  
        
            String TuzelKisiUnvani = "0";
            String Adres = ta_adres.getText();
            String Eposta = mail.getText();
            String Telefonu = telefon_num.getText();       
            String Adi = ad.getText();
            String Soyadi = soyad.getText();
            String Fax =  "null";
            String BasvuruAciklamasi = ta_bas_acıklama.getText();
            
            
            
            System.out.println("Ad: "+sqlInjection.injectionControl(Adi)+
            "Soyadi: "+sqlInjection.injectionControl(Soyadi)+
                    "Adres: "+sqlInjection.injectionControl(Adres)+
                    "Eposta: "+sqlInjection.injectionControl(Eposta)+
                    "Telefonu: "+sqlInjection.injectionControl(Telefonu)
            );
        
          
        if(sqlInjection.injectionControl(Adi) || sqlInjection.injectionControl(Soyadi) || sqlInjection.injectionControl(Adres) 
                || sqlInjection.injectionControl(Eposta) || sqlInjection.injectionControl(Telefonu)
                 || sqlInjection.injectionControl(pasaport_no.getText()) || sqlInjection.injectionControl(tc_no.getText())
                || sqlInjection.injectionControl(BasvuruAciklamasi) ) {
             
            JOptionPane.showMessageDialog(null, "Sql Injection Algınlandı!","UYARI!",JOptionPane.WARNING_MESSAGE);
            
        } else {
            
        
      	Map<String, Object> parameters = new HashMap<>();
	parameters.put("fieldAdis", "Adi,Soyadi,BasvuruTarihi,BasvuruCevapSonTarihi,BasvuranTipiNo,BasvuruTipiNo,BasvuruDurumuNo,TurkVatandasimi,TCKimlikNo,TuzelKisimi,TuzelKisiUnvani,Adres,Eposta,Telefonu,TelefonTipiNo,Fax,AdresTipiNo");
         String basvuru_no_ekrandaGösterilmesi="Select TOP 1 BasvuruNo from Basvuru ORDER BY BasvuruNo DESC ";
	List<Object> rows = new ArrayList<>();
      
        long tcNewVeri;
        
        if(uyruk.getSelectedIndex() == 0 ) 
            tcNewVeri = Long.parseLong(pasaport_no.getText());
        else 
            tcNewVeri = Long.parseLong(tc_no.getText());
        
            int kurum_no=0;
            String kurum_adi= (String) kurum_tipi_combo.getSelectedItem();
            
            try {
                ResultSet rs=SqlQuery("select KurumNo from Kurum where KurumAdi = " +"'"+kurum_adi+"'");
               if(rs.next())
               {
                   kurum_no=Integer.parseInt(rs.getString("KurumNo")) ;
                  
               }
               
               
            } catch (Exception ex) {
                Logger.getLogger(Basvuru_Ekrani.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
                        int BasvuranTipiNo = kisi_tanimi.getSelectedIndex();
                        int BasvuruTipiNo = basvuru_yolu.getSelectedIndex();
                        int BasvuruDurumuNo = 0;

                        int TurkVatandasimi = uyruk.getSelectedIndex(); //0 tc ,1 yabancı
                        long TCKimlikNo = tcNewVeri;

                        int TuzelKisimi = kisi_tanimi.getSelectedIndex();
       
                        int TelefonTipiNo = telefon_tip_combo.getSelectedIndex();
            
                        int AdresTipiNo = adres_combo.getSelectedIndex();  
                        
                        
                        int KurumNo = kurum_no; 
                        
                        int CevaplamaTipiNo = basvuru_yolu.getSelectedIndex();
                        
                        //if(tuzel_unvan.getText() == "") TuzelKisiUnvani = "NULL";
                        
            
           rows.add(new Basvuru(Adi, Soyadi,BasvuruTipiNo, BasvuruDurumuNo,TurkVatandasimi,TCKimlikNo, TuzelKisimi, TuzelKisiUnvani, Adres, Eposta, Telefonu, TelefonTipiNo, Fax,CevaplamaTipiNo, AdresTipiNo,BasvuruAciklamasi,KurumNo));           
                        

           
            basvuru1 = new Basvuru(Adi, Soyadi,BasvuruTipiNo, BasvuruDurumuNo,TurkVatandasimi,TCKimlikNo, TuzelKisimi, TuzelKisiUnvani, Adres, Eposta, Telefonu, TelefonTipiNo, Fax,CevaplamaTipiNo, AdresTipiNo,BasvuruAciklamasi,KurumNo);           
            
                String sql_query = "insert into Basvuru (Adi, Soyadi,BasvuruTipiNo, BasvuruDurumuNo,TurkVatandasimi,TCKimlikNo, TuzelKisimi, TuzelKisiUnvani, Adres, Eposta, Telefonu, TelefonTipiNo, Fax,CevaplamaTipiNo, AdresTipiNo,BasvuruAciklamasi,KurumNo)"
                    +"values ('"+
                        Adi                 +"','"+ 
                        Soyadi              +"',"+
                        BasvuruTipiNo       +", "+
                        BasvuruDurumuNo     +","+
                        TurkVatandasimi     +","+
                        TCKimlikNo          +", "+
                        TuzelKisimi         +", '"+
                        TuzelKisiUnvani     +"', '"+
                        Adres               +"', '"+
                        Eposta              +"', '"+
                        Telefonu            +"', "+
                        TelefonTipiNo       +", '"+
                        Fax                 +"',"+
                        CevaplamaTipiNo     +", "+
                        AdresTipiNo         +",'"+
                        BasvuruAciklamasi   +"',"+
                        KurumNo             +")";

          try {
                 SqlQuery2(sql_query);
         
           
             ResultSet rs=SqlQuery(basvuru_no_ekrandaGösterilmesi);
             String bas_no=null;
             while(rs.next())
             {
                  bas_no=rs.getString("BasvuruNo");
             }
          
             JOptionPane.showMessageDialog(null,"Basvuru "+bas_no+" numara ile kaydedildi\nSorgu yapmak için numarayı kaybetmeyin" , "Basvuru Kabul", JOptionPane.INFORMATION_MESSAGE);
         
             
          

        } catch (Exception ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
               
        basvuruArray.add(basvuru1);
            
      

	parameters.put("rows", rows);
        
      	Map<String, Controller> router = new HashMap<>();		
	router.put("Basvuru", new Controller(new BasvuruView(), new BasvuruModel()));
        
        ViewData veriEkle = new ViewData("Basvuru", "insert", parameters);
        try {
             Controller controller = router.get(veriEkle.functionName);
             ModelData modelData = controller.executeModel(veriEkle);
             veriEkle = controller.getView(modelData, veriEkle.functionName, veriEkle.operationName);
           

             
           } catch (Exception ex) { }   
        
    }
 
      
    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void uyrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyrukActionPerformed
       if(uyruk.getSelectedItem().equals("Yabancı"))
       {
           jLayeredPane1.setVisible(true);
           pasaport_pane.setVisible(true);
           tc_pane.setVisible(false);
       
       }
       else
       {
           jLayeredPane1.setVisible(true);
           pasaport_pane.setVisible(false);
           tc_pane.setVisible(true);
       
       }
    }//GEN-LAST:event_uyrukActionPerformed

    private void kisi_tanimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisi_tanimiActionPerformed
        if(kisi_tanimi.getSelectedIndex()==1)
        {
           
            gercek_tuzel_pane.setVisible(true);
            String tuzelUnvan=tuzel_unvan.getText(); 
        }
        else
        {
           
            gercek_tuzel_pane.setVisible(false);
        }
    }//GEN-LAST:event_kisi_tanimiActionPerformed

    private void telefon_tip_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefon_tip_comboActionPerformed
      
        
        
    }//GEN-LAST:event_telefon_tip_comboActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
       if(rb1.isSelected())
       {
          radio_btn_fill(0);
           for (int i = 0; i < kamu_arr.size(); i++) {
            kurum_tipi_combo.addItem(kamu_arr.get(i));
        }
       }
       
       
      
        
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
if(rb2.isSelected())
       {
          radio_btn_fill(1);
            for (int i = 0; i < kamu_arr.size(); i++) {
            kurum_tipi_combo.addItem(kamu_arr.get(i));
        }
       }
        
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   int result= JOptionPane.showConfirmDialog(null, "Çıkmak istediğine emin misin? ", "Uyarı",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
 if(result == JOptionPane.YES_OPTION)
 {
     this.setVisible(false);
     Login_Page login=new Login_Page();
     login.setVisible(true);
 }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pasaport_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasaport_noKeyPressed
    
        
    }//GEN-LAST:event_pasaport_noKeyPressed

    private void pasaport_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasaport_noKeyTyped
   
        char karakter=evt.getKeyChar();
        
        
        if(!(Character.isDigit(karakter)))
        {
    
            evt.consume();
         
        }    }//GEN-LAST:event_pasaport_noKeyTyped

    private void pasaport_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasaport_noKeyReleased
       
                   if (isTCKNCorrect(pasaport_no.getText())){
                 btn_kaydet.setEnabled(true);
             }else{
                  btn_kaydet.setEnabled(false);
             }
        
        
    }//GEN-LAST:event_pasaport_noKeyReleased
// Text'e girilenlerin rakam olmasını zorlama fonksiyonu
    private void tc_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tc_noKeyTyped
        char ch = evt.getKeyChar();
       
        if(!Character.isDigit(ch) )
        {
            evt.consume();
        }
    }//GEN-LAST:event_tc_noKeyTyped
//bu komutsatırı gerçek bir tc numarası girilmesinin hesaplamasını yapmaktadır.
  private boolean isTCKNCorrect(String id) {
      if (id == null) return false;

 

      if (id.length() != 11) return false;

 


//      char[] chars = id.toCharArray();
//      int[] a = new int[11];
//  
//      for(int i=0; i<11; i++) {
//          a[i] = chars[i] - '0';
//      }
//
//      if(a[0] == 0) return false;
//      if(a[10] % 2 == 1) return false;
//
//      if(((a[0] + a[2] + a[4] + a[6] + a[8]) * 7 - (a[1] + a[3] + a[5] + a[7])) % 10 != a[9]) return false;
//
//      if((a[0] + a[1] + a[2] + a[3] + a[4] + a[5] + a[6] + a[7] + a[8] + a[9]) % 10 != a[10]) return false;

 

      return true;
  }
    private void tc_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tc_noKeyReleased
             if (isTCKNCorrect(tc_no.getText())){
                 btn_kaydet.setEnabled(true);
             }else{
                  btn_kaydet.setEnabled(false);
             }
    }//GEN-LAST:event_tc_noKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basvuru_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basvuru_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basvuru_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basvuru_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basvuru_Ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ad;
    private javax.swing.JComboBox<String> adres_combo;
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> basvuru_yolu;
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JPanel gercek_tuzel_pane;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kisi_tanimi;
    private javax.swing.ButtonGroup kurum_tipi;
    public static javax.swing.JComboBox<String> kurum_tipi_combo;
    private javax.swing.JTextField mail;
    public static javax.swing.JTextField pasaport_no;
    private javax.swing.JPanel pasaport_pane;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    public static javax.swing.JTextField soyad;
    private javax.swing.JTextArea ta_adres;
    private javax.swing.JTextArea ta_bas_acıklama;
    private javax.swing.JTextField tc_no;
    private javax.swing.JPanel tc_pane;
    private javax.swing.JTextField telefon_num;
    public static javax.swing.JComboBox<String> telefon_tip_combo;
    private javax.swing.JTextField tuzel_unvan;
    private javax.swing.JComboBox<String> uyruk;
    // End of variables declaration//GEN-END:variables
}
